language: node_js
node_js:
  - "10.14.2"
cache:
  directories:
    - node_modules/
branches:
  only:
    - master
    - greenkeeper/
after_success:
  - codecov
  - yarn run build
  - yarn run semantic-release
